version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
#  pre_build:
#    commands:
#      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - gradle build
      - gradle bootJar
      - gradle war
#  post_build:
#    commands:
#      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/module4-thin.war