version: 0.2

env:
  parameter-store:
    SONAR_PROJECT_KEY: "SonarProjectKey"
    SONAR_ORG: "SonarOrganization"
    SONAR_HOST: "SonarHost"
  secrets-manager:
    SONAR_TOKEN: prod/sonar:SonarToken
    ARTIFACT_AUTH_TOKEN: prod/code-artifact:CodeArtifactAuthToken
phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
      - ./gradlew sonar "-Dsonar.projectKey=$SONAR_PROJECT_KEY" "-Dsonar.organization=$SONAR_ORG" "-Dsonar.host.url=$SONAR_HOST" "-Dsonar.token=$SONAR_TOKEN" "-Dsonar.qualitygate.wait=true"
artifacts:
  files:
    - module4-thin.war
  name: codebuild-artifact
  base-directory: build/libs
