spring:
  profiles:
    active: dev

logging:
  level:
    root: info

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#spring:
#  main:
#    allow-circular-references: true
#    allow-bean-definition-overriding: true
