server:
  error:
    path: /error

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1039367988334-nkbu8o2m2f8d4li6juk0vmner6jlbev1.apps.googleusercontent.com
            client-secret: ENC(OKg4gjRKW9jFXm0oRw7k7pq7ayjjm8+Afy1swsejlwCAqItWrqqM7XYTNWkOfEgX)
            redirect-uri: "{baseUrl}/oauth2/sign-in/callback/google"
            scope:
              - openid
              - email
              - profile
          github:
            client-id: 98ece16bca00b86ea22c
            client-secret: ENC(86Q6OplBBmC9MIyP8z0HP1jx7aibIbQu7II50f/Ltjp2gxTc/IR3ddyV5iXDJSA3E+SUCJ58ytQ=)
            redirect-uri: "{baseUrl}/oauth2/sign-in/callback/github"
            scope:
              - user:email
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#server:
#  port: 8080
#http:
#  host: localhost:8080
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#server:
#  port: 80
#http:
#  host: 3.76.207.37
