version: '3.9'
services:

  mysql:
    image: mysql:8.0
    container_name: module4-app-mysql-db
    ports:
      - "8083:3306"
    environment:
#      MYSQL_HOST: localhost1
      MYSQL_DATABASE: epam_lab_module_4
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: module4_app
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - module4-mysql-db-volume:/var/lib/mysql

  app:
#    image: amazoncorretto:17-alpine
    image: dan/myapp:latest
    container_name: module4-app
    ports:
      - "80:8080"
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - JAR_FILE=build/libs/module4-0.0.1-SNAPSHOT.jar
#    command: --spring.profiles.active=dev
    environment:
#      JAVA_OPTS: -Dspring.profiles.active=prod -Dserver.port=8080
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active": "dev",
        "server.port": "8080"
      }'

secrets:
  db_root_password:
    file: secrets/db_root_password.txt
  db_password:
    file: secrets/db_password.txt

volumes:
  module4-mysql-db-volume:
